name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t goutam363/test-react
    - run: echo "${{secrets.DOCKER_HUB_ACCESS_TOKEN}}" | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
    - run: docker push goutam363/test-react:latest

    - name: Deploy to SSH server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 10.30.9.120
        username: goutam
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker pull goutam363/test-react:latest
          docker stop react-app || true
          docker rm react-app || true
          docker run -d --name react-app -p 80:80 goutam363/test-react:latest